#!/usr/bin/env ruby

require 'open-uri'
require 'fileutils'
require 'shellwords'

# config.rb -- universal build.ninja generator
# Usage: ruby config.rb [debug|release]

MODE = (ARGV[0] || "debug").freeze

# --- DSL state ---
$libs = []
$exes = []
$amalgamates = []
$mode_cflags = {}
$extra_ninja = ""
$extra_defaults = []


def lib name, srcs:
  $libs << { name: name, srcs: srcs }
end

def exe name, srcs:, deps: [], ext_libs: [], extra_objs: [], order_deps: []
  $exes << { name: name, srcs: srcs, deps: deps, ext_libs: ext_libs, extra_objs: extra_objs, order_deps: order_deps }
end

def amalgamate name, src:, include_dirs: []
  $amalgamates << { src: src, output: name, include_dirs: include_dirs }
end

def debug cflags:
  $mode_cflags["debug"] = cflags
end

def release cflags:
  $mode_cflags["release"] = cflags
end

def coverage cflags:
  $mode_cflags["coverage"] = cflags
end

def ninja_raw text
  $extra_ninja << "#{text}\n"
end

def gen_str_header dst, from:
  $extra_ninja << "build #{dst}: gen_str_header #{from}\n"
end

def sh *cmd, **opts
  print "system "
  p cmd
  system *cmd, out: $stdout, err: $stderr, **opts or abort "sh failed"
end

# --- Ensure kissat is built (not needed on Windows, DSatur fallback used instead) ---
IS_WINDOWS = RUBY_PLATFORM =~ /mingw|mswin|cygwin/
KISSAT_LIB = "build/kissat/build/libkissat.a"
unless IS_WINDOWS || File.exist?(KISSAT_LIB)
  require 'tmpdir'
  require 'open-uri'
  version  = "rel-4.0.4"
  url      = "https://github.com/arminbiere/kissat/archive/refs/tags/#{version}.tar.gz"
  dest     = "build/kissat"
  FileUtils.mkdir_p("build")
  FileUtils.rm_rf(dest)
  puts "Downloading kissat #{version}..."
  tarball = "build/kissat.tar.gz"
  URI.open(url) { |src| File.binwrite(tarball, src.read) }
  sh "tar", "xzf", tarball, "-C", "build", "--exclude=*/test/cnf/hard.cnf"
  File.delete(tarball)
  File.rename("build/kissat-#{version}", dest)
  Dir.chdir dest do
    sh "./configure"
    sh "make"
  end
  puts "Done: #{KISSAT_LIB}"
end

# --- Ensure subprocess.h is available ---
SUBPROCESS_H = "build/subprocess.h"
unless File.exist?(SUBPROCESS_H)
  require 'open-uri'
  FileUtils.mkdir_p("build")
  url = "https://raw.githubusercontent.com/sheredom/subprocess.h/b49c56e9fe214488493021017bf3954b91c7c1f5/subprocess.h"
  puts "Downloading subprocess.h..."
  URI.open(url) { |src| File.binwrite(SUBPROCESS_H, src.read) }
  puts "Done: #{SUBPROCESS_H}"
end

# --- Detect toolchain ---
CC = ENV["CC"] || (RUBY_PLATFORM =~ /darwin/ ? "xcrun clang" : "clang")
AR = ENV["AR"] || "ar"
CLANG_FORMAT = RUBY_PLATFORM =~ /darwin/ ? "xcrun clang-format" : "clang-format"
ALL_SRCS = (Dir.glob '{src,test}/**/*.{c,h}').join ' '

ARCH_CFLAGS = RUBY_PLATFORM =~ /x86_64|amd64/ ? "-mavx2" : ""

llvm_cc = (RUBY_PLATFORM =~ /darwin/ ? "xcrun clang" : (ENV["CC"] || "clang"))

BASE_CFLAGS = %<
  -std=c23 -D_POSIX_C_SOURCE=200809L -DLLVM_CC="\\"#{llvm_cc}\\"" -Wall -Wextra -Werror -fvisibility=hidden #{ARCH_CFLAGS}
>.strip

BUILDDIR = "build/#{MODE}"

require_relative "config.in.rb"

EXTRA_CFLAGS = $mode_cflags.fetch(MODE, "")
CFLAGS = "#{BASE_CFLAGS} #{EXTRA_CFLAGS}".strip

link_flags = (EXTRA_CFLAGS.include?("sanitize") || EXTRA_CFLAGS.include?("coverage")) ? EXTRA_CFLAGS : ""

# --- Generate build.ninja ---
File.open "build.ninja", "w" do |f|
  f.puts <<-NINJA
# Generated by config.rb (mode=#{MODE})
builddir = #{BUILDDIR}

rule cc
  command = #{CC} #{CFLAGS} -MMD -MF $out.d -c $in -o $out
  depfile = $out.d
  description = CC $in

rule cc_test
  command = #{CC} #{CFLAGS} -DBUILD_DIR=\\\"#{BUILDDIR}\\\" -MMD -MF $out.d -c $in -o $out
  depfile = $out.d
  description = CC $in

rule ar
  command = #{AR} rcs $out $in
  description = AR $out

rule gen_nest_lex
  command = $in $out
  description = GEN $out

rule ll_cc
  command = #{CC} -c $in -o $out
  description = LLCC $in

rule gen_str_header
  command = ruby scripts/gen_str_header.rb $in $out
  description = GEN_STR_HEADER $out

rule format
  command = #{CLANG_FORMAT} -i $in
  description = FORMAT

rule amalgamate
  command = ruby scripts/amalgamate.rb $flags $in $out
  description = AMALGAMATE $out

rule link
  command = #{CC} #{link_flags} $in -o $out
  description = LINK $out

build format: format #{ALL_SRCS}

build #{BUILDDIR}/nest_lex.ll: gen_nest_lex #{BUILDDIR}/parse_gen
build #{BUILDDIR}/nest_lex.o: ll_cc #{BUILDDIR}/nest_lex.ll

build #{BUILDDIR}/llir_lex.ll: gen_nest_lex #{BUILDDIR}/llir_parse_gen
build #{BUILDDIR}/llir_lex.o: ll_cc #{BUILDDIR}/llir_lex.ll

  NINJA


  lib_outputs = {}
  emitted = {}

  # Libraries
  $libs.each do |lib|
    objs = lib[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      unless emitted[obj]
        f.puts "build #{obj}: cc #{src}"
        emitted[obj] = true
      end
      obj
    end
    ar_out = "#{BUILDDIR}/lib#{lib[:name]}.a"
    f.puts "build #{ar_out}: ar #{objs.join(' ')}"
    f.puts ""
    lib_outputs[lib[:name]] = ar_out
  end

  # Collect order-only deps per object across all executables
  obj_order_deps = Hash.new { |h, k| h[k] = [] }
  $exes.each do |exe|
    next if exe[:order_deps].empty?
    exe[:srcs].each do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      obj_order_deps[obj] |= exe[:order_deps]
    end
  end

  # Executables
  $exes.each do |exe|
    objs = exe[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      unless emitted[obj]
        rule = src.start_with?("test/") ? "cc_test" : "cc"
        od = obj_order_deps[obj]
        order_suffix = od.empty? ? "" : " || #{od.join(' ')}"
        f.puts "build #{obj}: #{rule} #{src}#{order_suffix}"
        emitted[obj] = true
      end
      obj
    end
    dep_archives = exe[:deps].map { |d| lib_outputs[d] }.compact
    all_inputs = (objs + dep_archives + exe[:extra_objs] + exe[:ext_libs]).join(' ')
    out = "#{BUILDDIR}/#{exe[:name]}"
    f.puts "build #{out}: link #{all_inputs}"
    f.puts ""
  end

  # Amalgamate
  $amalgamates.each do |am|
    flags = am[:include_dirs].map { |d| "-i #{d}" }.join(' ')
    src_files = am[:src].join(' ')
    dep_files = Dir.glob(am[:include_dirs].map { |d| "#{d}/*.{c,h}" }).sort.join(' ')
    f.puts "build #{am[:output]}: amalgamate #{src_files} | #{dep_files}"
    f.puts "  flags = #{flags}"
    f.puts ""
  end

  # Extra ninja rules from config.in.rb
  f.puts $extra_ninja unless $extra_ninja.empty?

  # Default: build everything
  all = $exes.map { |e| "#{BUILDDIR}/#{e[:name]}" }
  all += $amalgamates.map { |am| am[:output] }
  all += $extra_defaults
  f.puts "default #{all.join(' ')}"
end

puts "Generated build.ninja (mode=#{MODE}, cc=#{CC})"

sh "ninja -t compdb cc cc_test > compile_commands.json"
