#!/usr/bin/env ruby

require 'open-uri'
require 'fileutils'

# config.rb -- universal build.ninja generator
# Usage: ruby config.rb [debug|release]

MODE = (ARGV[0] || "debug").freeze

# --- DSL state ---
$libs = []
$exes = []
$amalgamates = []
$mode_cflags = {}
$extra_ninja = ""
$extra_defaults = []


def lib(name, srcs:)
  $libs << { name: name, srcs: srcs }
end

def exe(name, srcs:, deps: [], ext_libs: [], extra_objs: [])
  $exes << { name: name, srcs: srcs, deps: deps, ext_libs: ext_libs, extra_objs: extra_objs }
end

def amalgamate(name, input:, include_dirs: [])
  $amalgamates << { input: input, output: name, include_dirs: include_dirs }
end

def debug(cflags:)
  $mode_cflags["debug"] = cflags
end

def release(cflags:)
  $mode_cflags["release"] = cflags
end

def coverage(cflags:)
  $mode_cflags["coverage"] = cflags
end

def ninja_raw(text)
  $extra_ninja << "#{text}\n"
end

def gen_str_header dst, from:
  $extra_ninja << "build #{dst}: gen_str_header #{from}\n"
end

def sh *cmd, **opts
  print "system "
  p cmd
  system *cmd, out: $stdout, err: $stderr, **opts or abort "sh failed"
end

# --- Ensure kissat is built (not needed on Windows, DSatur fallback used instead) ---
IS_WINDOWS = RUBY_PLATFORM =~ /mingw|mswin|cygwin/
KISSAT_LIB = "build/kissat/build/libkissat.a"
unless IS_WINDOWS || File.exist?(KISSAT_LIB)
  require 'tmpdir'
  require 'open-uri'
  version  = "rel-4.0.4"
  url      = "https://github.com/arminbiere/kissat/archive/refs/tags/#{version}.tar.gz"
  dest     = "build/kissat"
  FileUtils.mkdir_p("build")
  FileUtils.rm_rf(dest)
  puts "Downloading kissat #{version}..."
  tarball = "build/kissat.tar.gz"
  URI.open(url) { |src| File.binwrite(tarball, src.read) }
  sh "tar", "xzf", tarball, "-C", "build", "--exclude=*/test/cnf/hard.cnf"
  File.delete(tarball)
  File.rename("build/kissat-#{version}", dest)
  Dir.chdir dest do
    sh "./configure"
    sh "make"
  end
  puts "Done: #{KISSAT_LIB}"
end

# --- Detect toolchain ---
CC = ENV["CC"] || (RUBY_PLATFORM =~ /darwin/ ? "xcrun clang" : "clang")
AR = ENV["AR"] || "ar"
CLANG_FORMAT = RUBY_PLATFORM =~ /darwin/ ? "xcrun clang-format" : "clang-format"
ALL_SRCS = (Dir.glob '{src,test}/**/*.{c,h}').join ' '

ARCH_CFLAGS = RUBY_PLATFORM =~ /x86_64|amd64/ ? "-mavx2" : ""

def default_host_triple
  triple_cmd =
    if IS_WINDOWS
      "#{CC} --print-target-triple 2>nul"
    else
      "#{CC} --print-target-triple 2>/dev/null"
    end
  t = `#{triple_cmd}`.strip
  return t unless t.empty?

  case RUBY_PLATFORM
  when /darwin/
    arch = `uname -m`.strip
    arch == "arm64" ? "arm64-apple-darwin" : "x86_64-apple-darwin"
  when /mingw|mswin|cygwin/
    "x86_64-pc-windows-msvc"
  when /linux/
    arch = `uname -m`.strip
    arch = "x86_64" if arch.empty?
    "#{arch}-unknown-linux-gnu"
  else
    "x86_64-unknown-linux-gnu"
  end
end

DEFAULT_HOST_TRIPLE = default_host_triple

BASE_CFLAGS = "-std=c23 -D_POSIX_C_SOURCE=200809L -DDEFAULT_TRIPLE=\\\"#{DEFAULT_HOST_TRIPLE}\\\" -Wall -Wextra -Werror -fvisibility=hidden #{ARCH_CFLAGS}".strip

BUILDDIR = "build/#{MODE}"

require_relative "config.in.rb"

EXTRA_CFLAGS = $mode_cflags.fetch(MODE, "")
CFLAGS = "#{BASE_CFLAGS} #{EXTRA_CFLAGS}".strip

# --- Ensure amalgamate tool is available ---

def amalgamate_url
  base = "https://github.com/rindeal/Amalgamate/releases/download/v0.99.0"
  case RUBY_PLATFORM
  when /darwin/
    "#{base}/amalgamate-v0.99.0-darwin-arm64.zip"
  when /mingw|mswin|cygwin/
    "#{base}/amalgamate-v0.99.0-windows-amd64.zip"
  else
    "#{base}/amalgamate-v0.99.0-linux-amd64.zip"
  end
end

TOOL_BIN = "build/tools/amalgamate"

unless File.executable?(TOOL_BIN)
  FileUtils.mkdir_p("build/tools")
  zip_path = "build/tools/amalgamate.zip"
  puts "Downloading amalgamate..."
  URI.open(amalgamate_url) do |remote|
    File.binwrite(zip_path, remote.read)
  end
  sh "unzip", "-o", zip_path, "-d", "build/tools/", out: File::NULL
  # The zip contains a subdirectory; move the binary up
  Dir.glob("build/tools/*/amalgamate").each do |bin|
    FileUtils.mv(bin, TOOL_BIN)
  end
  FileUtils.chmod(0o755, TOOL_BIN) unless RUBY_PLATFORM =~ /mingw|mswin|cygwin/
  FileUtils.rm_f(zip_path)
end

llvm_cc = RUBY_PLATFORM =~ /darwin/ ? "xcrun clang" : (ENV["CC"] || "clang")

# --- Generate build.ninja ---
File.open("build.ninja", "w") do |f|
  f.puts <<-NINJA
# Generated by config.rb (mode=#{MODE})
builddir = #{BUILDDIR}

rule cc
  command = #{CC} #{CFLAGS} -MMD -MF $out.d -c $in -o $out
  depfile = $out.d
  description = CC $in

rule cc_test
  command = #{CC} #{CFLAGS} -DBUILD_DIR=\\\"#{BUILDDIR}\\\" -MMD -MF $out.d -c $in -o $out
  depfile = $out.d
  description = CC $in

rule ar
  command = #{AR} rcs $out $in
  description = AR $out

rule gen_nest_lex
  command = $in $out
  description = GEN $out

rule ll_cc
  command = #{CC} -c $in -o $out
  description = LLCC $in

rule gen_str_header
  command = ruby scripts/gen_str_header.rb $in $out
  description = GEN_STR_HEADER $out

rule format
  command = #{CLANG_FORMAT} -i $in
  description = FORMAT

build format: format #{ALL_SRCS}

build #{BUILDDIR}/nest_lex.ll: gen_nest_lex #{BUILDDIR}/parse_gen
build #{BUILDDIR}/nest_lex.o: ll_cc #{BUILDDIR}/nest_lex.ll

  NINJA

  link_flags = (EXTRA_CFLAGS.include?("sanitize") || EXTRA_CFLAGS.include?("coverage")) ? EXTRA_CFLAGS : ""
  f.puts "rule link"
  f.puts "  command = #{CC} #{link_flags} $in -o $out"
  f.puts "  description = LINK $out"
  f.puts ""

  lib_outputs = {}
  emitted = {}

  # Libraries
  $libs.each do |lib|
    objs = lib[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      unless emitted[obj]
        f.puts "build #{obj}: cc #{src}"
        emitted[obj] = true
      end
      obj
    end
    ar_out = "#{BUILDDIR}/lib#{lib[:name]}.a"
    f.puts "build #{ar_out}: ar #{objs.join(' ')}"
    f.puts ""
    lib_outputs[lib[:name]] = ar_out
  end

  # Executables
  $exes.each do |exe|
    objs = exe[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      unless emitted[obj]
        rule = src.start_with?("test/") ? "cc_test" : "cc"
        f.puts "build #{obj}: #{rule} #{src}"
        emitted[obj] = true
      end
      obj
    end
    dep_archives = exe[:deps].map { |d| lib_outputs[d] }.compact
    all_inputs = (objs + dep_archives + exe[:extra_objs] + exe[:ext_libs]).join(' ')
    out = "#{BUILDDIR}/#{exe[:name]}"
    f.puts "build #{out}: link #{all_inputs}"
    f.puts ""
  end

  # Amalgamate
  unless $amalgamates.empty?
    f.puts "rule amalgamate"
    f.puts "  command = #{TOOL_BIN} $flags $in $out"
    f.puts "  description = AMALGAMATE $out"
    f.puts ""

    $amalgamates.each do |am|
      flags = am[:include_dirs].map { |d| "-i #{d}" }.join(' ')
      src_files = Dir.glob(am[:include_dirs].map { |d| "#{d}/*.{c,h}" }).sort.join(' ')
      f.puts "build #{am[:output]}: amalgamate #{am[:input]} | #{src_files}"
      f.puts "  flags = #{flags}"
      f.puts ""
    end
  end

  # Extra ninja rules from config.in.rb
  f.puts $extra_ninja unless $extra_ninja.empty?

  # Default: build everything
  all = $exes.map { |e| "#{BUILDDIR}/#{e[:name]}" }
  all += $amalgamates.map { |am| am[:output] }
  all += $extra_defaults
  f.puts "default #{all.join(' ')}"
end

puts "Generated build.ninja (mode=#{MODE}, cc=#{CC})"

# --- Generate compile_commands.json ---
require 'json'

project_root = File.expand_path(__dir__)
all_srcs = ($libs.flat_map { |l| l[:srcs] } + $exes.flat_map { |e| e[:srcs] }).uniq
test_define = "-DBUILD_DIR=\\\"#{BUILDDIR}\\\""

entries = all_srcs.map do |src|
  extra = src.start_with?("test/") ? " #{test_define}" : ""
  {
    directory: project_root,
    file: src,
    command: "#{CC} #{CFLAGS}#{extra} -c #{src} -o #{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
  }
end

File.write("compile_commands.json", JSON.pretty_generate(entries) + "\n")
puts "Generated compile_commands.json"
