// specs/rt_ir.md — Runtime IR compilation
// State machine that processes clang LLVM IR output.
// Uses DFA lexer generated by llir_parse_gen.c.
#include "darray.h"
#include "irwriter.h"
#include <ctype.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define SUBPROCESS_IMPLEMENTATION
#include "../build/subprocess.h"

#include "../build/nest_rt_impl.inc"

// Token IDs — must match llir_parse_gen.c
enum {
  LLIR_TOK_SOURCE_FILENAME = 1,
  LLIR_TOK_DEFINE = 2,
  LLIR_TOK_DEFINE_INTERNAL = 3,
  LLIR_TOK_DECLARE = 4,
  LLIR_TOK_META_MODULE_FLAGS = 5,
  LLIR_TOK_META_LLVM_IDENT = 6,
  LLIR_TOK_META_DIFILE = 7,
  LLIR_TOK_META_NUMBERED = 8,
  LLIR_TOK_BRACE_CLOSE = 9,
};

// State machine states per spec
typedef enum {
  IR_STATE_NORMAL,
  IR_STATE_IN_FUNC,
} IRState;

// public API functions that should NOT be marked internal
// spec: ustr_*, tt_locate, darray_size
static bool _is_public_fn(const char* name) {
  if (strncmp(name, "ustr_", 5) == 0) {
    return true;
  }
  if (strcmp(name, "tt_locate") == 0) {
    return true;
  }
  if (strcmp(name, "darray_size") == 0) {
    return true;
  }
  return false;
}

// Extract function name from @name( pattern into name_buf. Returns length or 0.
static size_t _extract_fn_name(const char* start, char* buf, size_t buf_size) {
  const char* at = strchr(start, '@');
  if (!at) {
    return 0;
  }
  at++;
  const char* paren = strchr(at, '(');
  if (!paren || paren <= at) {
    return 0;
  }
  size_t len = (size_t)(paren - at);
  if (len >= buf_size) {
    return 0;
  }
  memcpy(buf, at, len);
  buf[len] = '\0';
  return len;
}

// DFA lexer function generated by llir_parse_gen — linked from llir_lex.o
// Returns {next_state, action_or_minus2}
typedef struct {
  int64_t state;
  int64_t action;
} LexResult;
extern LexResult lex_llir(int64_t state, int64_t cp);

// Lex a line prefix using the DFA. Returns the token ID (action_id) for the line.
static int32_t _lex_line(const char* line) {
  int64_t st = 0;
  int64_t last_action = -2;
  for (const char* p = line; *p && *p != '\n'; p++) {
    LexResult r = lex_llir(st, (int64_t)(unsigned char)*p);
    if (r.action > 0) {
      last_action = r.action;
    }
    if (r.state < 0) {
      break; // dead state
    }
    st = r.state;
  }
  // End of line — check final action
  LexResult r = lex_llir(st, -1); // EOF
  if (r.action > 0) {
    last_action = r.action;
  }
  return (int32_t)last_action;
}

// Rewrite !DIFile: replace filename with "nest", directory with given directory
static void _rewrite_difile(FILE* out, const char* line, const char* directory) {
  const char* fn_start = strstr(line, "filename:");
  if (!fn_start) {
    fputs(line, out);
    return;
  }
  const char* q1 = strchr(fn_start, '"');
  if (!q1) {
    fputs(line, out);
    return;
  }
  const char* q2 = strchr(q1 + 1, '"');
  if (!q2) {
    fputs(line, out);
    return;
  }
  fwrite(line, 1, (size_t)(q1 + 1 - line), out);
  fputs("nest", out);
  const char* dir_start = strstr(q2, "directory:");
  if (dir_start) {
    const char* dq1 = strchr(dir_start, '"');
    if (dq1) {
      const char* dq2 = strchr(dq1 + 1, '"');
      if (dq2) {
        fwrite(q2, 1, (size_t)(dq1 + 1 - q2), out);
        fputs(directory, out);
        fputs(dq2, out);
        return;
      }
    }
  }
  fputs(q2, out);
}

// Track metadata number from "!NN = ..." lines
static int32_t _track_meta_num(const char* line, int32_t max_meta) {
  const char* p = line + 1;
  if (!isdigit((unsigned char)*p)) {
    return max_meta;
  }
  int32_t num = 0;
  while (isdigit((unsigned char)*p)) {
    num = num * 10 + (*p - '0');
    p++;
  }
  return num > max_meta ? num : max_meta;
}

// State machine context
typedef struct {
  IRState state;
  int32_t max_meta;
  char* module_flags;
  const char* directory;
  bool had_source_filename;
} IrProcessCtx;

// Process one line of clang LLVM IR using state machine + DFA lexer.
static void _process_line(FILE* out, const char* line, IrProcessCtx* ctx, const char* source_file, IrWriter* w) {
  // In function body — forward everything until closing brace
  if (ctx->state == IR_STATE_IN_FUNC) {
    if (line[0] == '}') {
      ctx->state = IR_STATE_NORMAL;
    }
    fputs(line, out);
    return;
  }

  // Normal state — lex the line prefix to classify
  int32_t tok = _lex_line(line);

  switch (tok) {
  case LLIR_TOK_SOURCE_FILENAME:
    if (!ctx->had_source_filename) {
      fprintf(out, "source_filename = \"%s\"\n", source_file);
      ctx->had_source_filename = true;
    }
    return;

  case LLIR_TOK_DEFINE: {
    char name_buf[256];
    if (_extract_fn_name(line + 7, name_buf, sizeof(name_buf))) {
      irwriter_pre_define(w, name_buf);
      ctx->state = IR_STATE_IN_FUNC;
      if (!_is_public_fn(name_buf)) {
        fputs("define internal ", out);
        fputs(line + 7, out);
        return;
      }
    }
    ctx->state = IR_STATE_IN_FUNC;
    fputs(line, out);
    return;
  }

  case LLIR_TOK_DEFINE_INTERNAL: {
    char name_buf[256];
    if (_extract_fn_name(line + 16, name_buf, sizeof(name_buf))) {
      irwriter_pre_define(w, name_buf);
    }
    ctx->state = IR_STATE_IN_FUNC;
    fputs(line, out);
    return;
  }

  case LLIR_TOK_DECLARE: {
    char name_buf[256];
    if (_extract_fn_name(line + 8, name_buf, sizeof(name_buf))) {
      irwriter_pre_define(w, name_buf);
    }
    fputs(line, out);
    return;
  }

  case LLIR_TOK_META_MODULE_FLAGS: {
    // Capture inner refs, suppress the line
    const char* open = strchr(line, '{');
    const char* close = strrchr(line, '}');
    if (open && close && close > open + 1) {
      free(ctx->module_flags);
      size_t len = (size_t)(close - open - 1);
      ctx->module_flags = malloc(len + 1);
      memcpy(ctx->module_flags, open + 1, len);
      ctx->module_flags[len] = '\0';
    }
    return;
  }

  case LLIR_TOK_META_LLVM_IDENT:
    // Suppress
    return;

  case LLIR_TOK_META_NUMBERED:
    ctx->max_meta = _track_meta_num(line, ctx->max_meta);
    // Check for !DIFile in this metadata line
    if (strstr(line, "!DIFile(")) {
      _rewrite_difile(out, line, ctx->directory);
      return;
    }
    fputs(line, out);
    return;

  default:
    // Forward everything else
    fputs(line, out);
    return;
  }
}

// Tokenize a string by whitespace into a darray of char*.
// Returns newly allocated copies; caller frees the darray and each element.
static char** _tokenize(const char* str) {
  char** arr = darray_new(sizeof(char*), 0);
  const char* p = str;
  while (*p) {
    while (*p == ' ' || *p == '\t') {
      p++;
    }
    if (!*p) {
      break;
    }
    const char* start = p;
    while (*p && *p != ' ' && *p != '\t') {
      p++;
    }
    size_t len = (size_t)(p - start);
    char* tok = malloc(len + 1);
    memcpy(tok, start, len);
    tok[len] = '\0';
    darray_push(arr, tok);
  }
  return arr;
}

static void _free_tokens(char** arr) {
  size_t n = darray_size(arr);
  for (size_t i = 0; i < n; i++) {
    free(arr[i]);
  }
  darray_del(arr);
}

// Read all from subprocess stream into malloc'd buffer. Sets *out_len.
static char* _read_all(struct subprocess_s* proc, unsigned (*read_fn)(struct subprocess_s*, char*, unsigned),
                       size_t* out_len) {
  char* buf = NULL;
  size_t len = 0, cap = 0;
  char chunk[4096];
  unsigned n;
  while ((n = read_fn(proc, chunk, sizeof(chunk))) > 0) {
    if (len + n > cap) {
      cap = (len + n) * 2;
      buf = realloc(buf, cap + 1);
    }
    memcpy(buf + len, chunk, n);
    len += n;
  }
  if (buf) {
    buf[len] = '\0';
  }
  *out_len = len;
  return buf;
}

static void _pipe_to_cc_and_process(IrWriter* w, const char* c_source, size_t c_source_len, const char* source_file,
                                    const char* directory) {
  const char* cc = getenv("CC");
  if (!cc || !*cc) {
    cc = "clang";
  }
  const char* cflags = getenv("CFLAGS");
  if (!cflags) {
    cflags = "";
  }

  // Build argv: [cc_tokens...] [cflags_tokens...] -S -emit-llvm -x c -o - -
  char** cc_toks = _tokenize(cc);
  char** cf_toks = _tokenize(cflags);
  const char** argv = darray_new(sizeof(const char*), 0);
  for (size_t i = 0; i < darray_size(cc_toks); i++) {
    darray_push(argv, cc_toks[i]);
  }
  for (size_t i = 0; i < darray_size(cf_toks); i++) {
    darray_push(argv, cf_toks[i]);
  }
  const char* fixed[] = {"-S", "-emit-llvm", "-x", "c", "-o", "-", "-"};
  for (int i = 0; i < 7; i++) {
    darray_push(argv, fixed[i]);
  }
  const char* null_term = NULL;
  darray_push(argv, null_term);

  struct subprocess_s proc;
  int opts =
      subprocess_option_inherit_environment | subprocess_option_search_user_path | subprocess_option_enable_async;
  if (subprocess_create(argv, opts, &proc) != 0) {
    fprintf(stderr, "irwriter_gen_rt: failed to run compiler: %s\n", cc);
    darray_del(argv);
    _free_tokens(cc_toks);
    _free_tokens(cf_toks);
    abort();
  }

  // Write C source to stdin, then close stdin
  FILE* child_stdin = subprocess_stdin(&proc);
  if (c_source_len > 0) {
    fwrite(c_source, 1, c_source_len, child_stdin);
  }
  fclose(child_stdin);

  // Read all stdout and stderr
  size_t out_len = 0, err_len = 0;
  char* out_buf = _read_all(&proc, subprocess_read_stdout, &out_len);
  char* err_buf = _read_all(&proc, subprocess_read_stderr, &err_len);

  int exit_code = -1;
  subprocess_join(&proc, &exit_code);
  subprocess_destroy(&proc);

  darray_del(argv);
  _free_tokens(cc_toks);
  _free_tokens(cf_toks);

  // Abort on non-zero exit or any stderr output
  if (exit_code != 0 || err_len > 0) {
    fprintf(stderr, "irwriter_gen_rt: compiler %s\n", exit_code != 0 ? "failed" : "produced unexpected output");
    if (out_len > 0) {
      fprintf(stderr, "stdout:\n");
      fwrite(out_buf, 1, out_len, stderr);
    }
    if (err_len > 0) {
      fprintf(stderr, "stderr:\n");
      fwrite(err_buf, 1, err_len, stderr);
    }
    free(out_buf);
    free(err_buf);
    abort();
  }
  free(err_buf);

  // Process the IR from stdout line by line
  FILE* out = irwriter_get_file(w);
  IrProcessCtx ctx = {.state = IR_STATE_NORMAL, .max_meta = -1, .directory = directory};
  char* p = out_buf;
  while (p && *p) {
    char* nl = strchr(p, '\n');
    if (nl) {
      size_t line_len = (size_t)(nl - p + 1);
      char line[8192];
      if (line_len < sizeof(line)) {
        memcpy(line, p, line_len);
        line[line_len] = '\0';
        _process_line(out, line, &ctx, source_file, w);
      } else {
        // Long line: copy to heap
        char* heap_line = malloc(line_len + 1);
        memcpy(heap_line, p, line_len);
        heap_line[line_len] = '\0';
        _process_line(out, heap_line, &ctx, source_file, w);
        free(heap_line);
      }
      p = nl + 1;
    } else {
      // Last line without newline
      _process_line(out, p, &ctx, source_file, w);
      break;
    }
  }
  free(out_buf);

  // Emit combined !llvm.module.flags + debug base metadata
  {
    int32_t id = ctx.max_meta + 1;
    int file_id = id++;
    int cu_id = id++;
    int type_id = id++;
    int dwarf_id = id++;
    int dbgver_id = id++;

    if (ctx.module_flags) {
      fprintf(out, "!llvm.module.flags = !{%s, !%d, !%d}\n", ctx.module_flags, dwarf_id, dbgver_id);
    } else {
      fprintf(out, "!llvm.module.flags = !{!%d, !%d}\n", dwarf_id, dbgver_id);
    }
    fprintf(out, "!llvm.dbg.cu = !{!%d}\n\n", cu_id);
    fprintf(out, "!%d = !{i32 7, !\"Dwarf Version\", i32 5}\n", dwarf_id);
    fprintf(out, "!%d = !{i32 2, !\"Debug Info Version\", i32 3}\n", dbgver_id);
    fprintf(out, "!%d = !DIFile(filename: \"%s\", directory: \"%s\")\n", file_id, source_file, directory);
    fprintf(out,
            "!%d = distinct !DICompileUnit(language: DW_LANG_C11, file: !%d,"
            " producer: \"dfa_gen\", isOptimized: true, runtimeVersion: 0,"
            " emissionKind: FullDebug)\n",
            cu_id, file_id);
    fprintf(out, "!%d = !DISubroutineType(types: !{null})\n\n", type_id);

    free(ctx.module_flags);

    irwriter_start(w, id, source_file, directory);
    irwriter_set_dbg_base(w, file_id, cu_id, type_id);
  }
}

void irwriter_gen_rt(IrWriter* w, const char* source_file, const char* directory) {
  _pipe_to_cc_and_process(w, (const char*)NEST_RT_IMPL, sizeof(NEST_RT_IMPL) - 1, source_file, directory);
}

void irwriter_gen_rt_simple(IrWriter* w) {
  static const char empty_src[] = "";
  _pipe_to_cc_and_process(w, empty_src, 0, "nest", ".");
}
